### ISSUE TITLE
关于您的职业的提问

### ISSUE THREAD

**Issue by Aniark** [MoyuScript/MoyuScript#11]
在下某日网上冲浪时，无意间看到了您过去的博文：[二本文科专业转行前端开发进入大厂经历分享](https://moyuscript.github.io/MoyuScript/2022/05/04/go-netease-share)

但是在您的此 [commit](https://github.com/MoyuScript/MoyuScript/commit/6dc0e8bb1f10949fc604475665a81e813403a540) 中，将“职业”变更为了“灵活就业人员” 

遂好奇，是什么原因使您离开了网易？

**Comment by MoyuScript** [comment]
裁员，包括我在内很多应届生都被裁员了，无关能力。剩下还留下的都是肯加班（普遍高强度九点后下班），接受PUA比较厉害的。

实际上我之前还有一篇文章：[找工作就是 90% 玄学 + 10% 实力](https://moyuscript.github.io/MoyuScript/2022/06/05/find-job-is-90-lucky-and-10-ability)，可以说我那会还没入职只是实习了段时间就已经意识到这个问题了。一个小逸闻：我被裁了告知身边同事普遍都以为我在开玩笑（也许是真心这么觉得），毕竟我的能力在他们看来是很强的，但我自己却一点都不意外，早就有预料了。在我预料到可能被裁员的风险后，我马上把自己所有债务（没有很多，主要是信用卡分期啥的）都清了，然后做好了储蓄计划，所以现在余量还够摆烂一两年。

不过接下来打算年后投投简历看看有没有机会，不过不抱多高期望，毕竟国内经济形势越来越差，真的和个人能力没多大关系。
